// Generated by Sterling SDK Generator — test suite
// Task Manager API v0.2.0

//! Integration-style tests for the generated client.
//! Each test spins up a lightweight HTTP server to capture the request.

use taskmanager-sdk::client::Client;
use std::sync::{Arc, Mutex};
use std::io::{Read, Write};
use std::net::TcpListener;

/// Captured HTTP request info.
#[derive(Debug, Clone, Default)]
struct CapturedRequest {
    method: String,
    path: String,
    body: String,
}

/// Start a simple single-request HTTP server that responds with 200 OK.
/// Returns (addr, captured) so tests can inspect what was received.
fn mock_server() -> (String, Arc<Mutex<CapturedRequest>>) {
    let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
    let addr = format!("http://{}", listener.local_addr().unwrap());
    let cap = Arc::new(Mutex::new(CapturedRequest::default()));
    let cap2 = Arc::clone(&cap);
    std::thread::spawn(move || {
        // Accept one connection
        if let Ok((mut stream, _)) = listener.accept() {
            let mut buf = [0u8; 4096];
            let n = stream.read(&mut buf).unwrap_or(0);
            let raw = String::from_utf8_lossy(&buf[..n]).to_string();
            // Parse first line: "METHOD /path HTTP/1.1"
            if let Some(first_line) = raw.lines().next() {
                let parts: Vec<&str> = first_line.split_whitespace().collect();
                if parts.len() >= 2 {
                    let mut c = cap2.lock().unwrap();
                    c.method = parts[0].to_string();
                    c.path = parts[1].to_string();
                }
            }
            // Extract body (after \r\n\r\n)
            if let Some(idx) = raw.find("\r\n\r\n") {
                let mut c = cap2.lock().unwrap();
                c.body = raw[idx + 4..].to_string();
            }
            let response = "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: 2\r\n\r\n{}";
            let _ = stream.write_all(response.as_bytes());
        }
    });
    // Small delay to let the server thread start
    std::thread::sleep(std::time::Duration::from_millis(50));
    (addr, cap)
}

/// Start a mock server that returns a specific status code.
fn mock_error_server(status: u16) -> String {
    let listener = TcpListener::bind("127.0.0.1:0").expect("bind");
    let addr = format!("http://{}", listener.local_addr().unwrap());
    std::thread::spawn(move || {
        if let Ok((mut stream, _)) = listener.accept() {
            let mut buf = [0u8; 4096];
            let _ = stream.read(&mut buf);
            let body = r#"{"message":"error"}"#;
            let resp = format!(
                "HTTP/1.1 {} Error\r\nContent-Type: application/json\r\nContent-Length: {}\r\n\r\n{}",
                status,
                body.len(),
                body
            );
            let _ = stream.write_all(resp.as_bytes());
        }
    });
    std::thread::sleep(std::time::Duration::from_millis(50));
    addr
}

#[tokio::test]
async fn test_list_tasks() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.list_tasks(None, None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "list_tasks should use GET");
    assert!(c.path.starts_with("/"), "list_tasks path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_create_task() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.create_task(&serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "create_task should use POST");
    assert!(c.path.starts_with("/"), "create_task path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_get_task() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.get_task("test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "GET", "get_task should use GET");
    assert!(c.path.starts_with("/"), "get_task path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_delete_task() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.delete_task("test-id", None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "DELETE", "delete_task should use DELETE");
    assert!(c.path.starts_with("/"), "delete_task path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_update_task() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.update_task("test-id", &serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "PATCH", "update_task should use PATCH");
    assert!(c.path.starts_with("/"), "update_task path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_complete_task() {
    let (addr, cap) = mock_server();
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let _result = client.complete_task("test-id", &serde_json::json!({}), None).await;
    // Give time for the TCP handler
    tokio::time::sleep(std::time::Duration::from_millis(20)).await;
    let c = cap.lock().unwrap();
    assert_eq!(c.method, "POST", "complete_task should use POST");
    assert!(c.path.starts_with("/"), "complete_task path should start with /: {}", c.path);
}

#[tokio::test]
async fn test_error_non_2xx() {
    // Verify that non-2xx responses result in errors
    let addr = mock_error_server(400);
    let client = Client::new(&addr).with_api_key("test-key").with_max_retries(0);
    let result = client.list_tasks(None, None).await;
    // The reqwest-based client may or may not surface this as an error
    // depending on whether the operation deserializes the response.
    // At minimum the request should complete without panic.
    drop(result);
}
