// Generated by Sterling SDK Generator
// Task Manager API v0.2.0

use reqwest::Client as HttpClient;
use reqwest::header::{HeaderMap, HeaderName, HeaderValue};
use crate::models::*;
use std::collections::HashMap;
use std::time::Duration;

/// Per-request options that override client defaults.
#[derive(Debug, Clone, Default)]
pub struct RequestOptions {
    /// Additional headers to send with the request.
    /// Set a header value to an empty string to remove it.
    pub headers: Option<HashMap<String, String>>,
    /// Request timeout override.
    pub timeout: Option<Duration>,
}

/// Log level for the SDK client, matching VERS_LOG env var values.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum LogLevel {
    Off = 0,
    Error = 1,
    Warn = 2,
    Info = 3,
    Debug = 4,
}

impl LogLevel {
    fn from_env() -> Self {
        match std::env::var("VERS_LOG").ok().as_deref() {
            Some("debug") => LogLevel::Debug,
            Some("info") => LogLevel::Info,
            Some("warn") => LogLevel::Warn,
            Some("error") => LogLevel::Error,
            Some("off") => LogLevel::Off,
            _ => LogLevel::Warn,
        }
    }
}

pub struct Client {
    http: HttpClient,
    base_url: String,
    api_key: Option<String>,
    headers: HeaderMap,
    max_retries: u32,
    timeout: Duration,
    log_level: LogLevel,
}

/// Merge multiple header maps. Later sources override earlier ones (case-insensitive).
/// A `None` value in the override map removes that header.
fn merge_headers(base: &HeaderMap, overrides: &[(HeaderName, Option<HeaderValue>)]) -> HeaderMap {
    let mut merged = base.clone();
    for (name, value) in overrides {
        match value {
            None => { merged.remove(name); }
            Some(v) => { merged.insert(name.clone(), v.clone()); }
        }
    }
    merged
}

impl Client {
    pub fn new(base_url: &str) -> Self {
        let env_base = std::env::var("VERS_BASE_URL").ok();
        let env_key = std::env::var("VERS_API_KEY").ok();
        let actual_base = if base_url.is_empty() {
            env_base.unwrap_or_else(|| base_url.to_string())
        } else {
            base_url.to_string()
        };
        Self {
            http: HttpClient::new(),
            base_url: actual_base,
            api_key: env_key,
            headers: HeaderMap::new(),
            max_retries: 2,
            timeout: Duration::from_secs(30),
            log_level: LogLevel::from_env(),
        }
    }

    pub fn with_log_level(mut self, level: LogLevel) -> Self {
        self.log_level = level;
        self
    }

    pub fn with_api_key(mut self, key: &str) -> Self {
        self.api_key = Some(key.to_string());
        self
    }

    pub fn with_headers(mut self, headers: HeaderMap) -> Self {
        self.headers = headers;
        self
    }

    pub fn with_max_retries(mut self, retries: u32) -> Self {
        self.max_retries = retries;
        self
    }

    pub fn with_timeout(mut self, timeout: Duration) -> Self {
        self.timeout = timeout;
        self
    }

    /// Use a pre-configured `reqwest::Client` (e.g. with custom proxy, middleware, or TLS settings).
    pub fn with_http_client(mut self, client: HttpClient) -> Self {
        self.http = client;
        self
    }

    fn auth_header(&self) -> Option<String> {
        self.api_key.as_ref().map(|k| format!("Bearer {}", k))
    }

    fn is_retryable_status(status: u16) -> bool {
        status >= 500 || status == 408 || status == 409 || status == 429
    }

    fn retry_delay(attempt: u32) -> Duration {
        let base_ms = 500u64 * 2u64.pow(attempt);
        let jitter_ms = (base_ms as f64 * 0.25 * rand_jitter()) as u64;
        Duration::from_millis(base_ms + jitter_ms)
    }

    fn parse_retry_after(resp: &reqwest::Response) -> Option<Duration> {
        let value = resp.headers().get("retry-after")?.to_str().ok()?;
        if let Ok(seconds) = value.parse::<u64>() {
            let capped = seconds.min(60);
            return Some(Duration::from_secs(capped));
        }
        None
    }

    /// List all tasks
    pub async fn list_tasks(&self, params: Option<&ListTasksParams>, options: Option<&RequestOptions>) -> Result<TaskListResponse, crate::errors::SDKError> {
        let mut url = format!("{}{}", self.base_url, "/api/tasks");
        if let Some(p) = params {
            let mut pairs: Vec<String> = Vec::new();
            if let Some(ref v) = p.status {
                pairs.push(format!("status={}", v));
            }
            if let Some(ref v) = p.limit {
                pairs.push(format!("limit={}", v));
            }
            if !pairs.is_empty() {
                url.push('?');
                url.push_str(&pairs.join("&"));
            }
        }
        if self.log_level >= LogLevel::Debug {
            log::debug!("request: GET {}", url);
        }
        let effective_timeout = options.and_then(|o| o.timeout).unwrap_or(self.timeout);
        let idempotency_key = {
            let ts = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos();
            let jitter = (rand_jitter() * 1_000_000_000.0) as u64;
            format!("{:x}-{:x}", ts, jitter)
        };
        let is_mutating = matches!("GET", "POST" | "PUT" | "PATCH" | "DELETE");
        let mut last_err: Option<reqwest::Error> = None;
        let mut retry_after_used = false;
        for attempt in 0..=self.max_retries {
            if attempt > 0 && !retry_after_used {
                if self.log_level >= LogLevel::Info {
                    log::info!("retry attempt {}/{} for GET {}", attempt, self.max_retries, url);
                }
                tokio::time::sleep(Self::retry_delay(attempt - 1)).await;
            }
            retry_after_used = false;
            let mut default_headers = HeaderMap::new();
            default_headers.insert("user-agent", HeaderValue::from_str(&format!(
                "taskmanager-sdk/0.2.0 rust {}/{}",
                std::env::consts::OS,
                std::env::consts::ARCH,
            )).unwrap());
            if let Some(ref token) = self.auth_header() {
                default_headers.insert("authorization", HeaderValue::from_str(token).unwrap());
            }
            if is_mutating {
                default_headers.insert("x-idempotency-key", HeaderValue::from_str(&idempotency_key).unwrap());
            }
            // Merge default, client-level, and per-request headers
            let client_overrides: Vec<(HeaderName, Option<HeaderValue>)> = self.headers.iter()
                .map(|(k, v)| (k.clone(), Some(v.clone())))
                .collect();
            let merged = merge_headers(&default_headers, &client_overrides);
            let mut req = self.http.get(&url).timeout(effective_timeout).headers(merged);
            if let Some(opts) = options {
                if let Some(ref hdrs) = opts.headers {
                    for (k, v) in hdrs {
                        req = req.header(k.as_str(), v.as_str());
                    }
                }
            }
            match req.send().await {
                Ok(resp) => {
                    if self.log_level >= LogLevel::Debug {
                        log::debug!("response: {} for GET {}", resp.status().as_u16(), url);
                    }
                    let status = resp.status().as_u16();
                    if !Self::is_retryable_status(status) || attempt == self.max_retries {
                        // Check for error responses before attempting to deserialize
                        if status < 200 || status >= 300 {
                            let headers: Vec<(String, String)> = resp.headers().iter()
                                .map(|(k, v)| (k.to_string(), v.to_str().unwrap_or("").to_string()))
                                .collect();
                            let body = resp.text().await.unwrap_or_default();
                            if self.log_level >= LogLevel::Error {
                                log::error!("API error: {} GET {}", status, url);
                            }
                            return Err(crate::errors::SDKError::API(
                                crate::errors::APIError::from_response(status, headers, body)
                            ));
                        }
                        let content_length = resp.content_length().unwrap_or(1);
                        if content_length == 0 {
                            return Ok(serde_json::from_str("{}").unwrap());
                        }
                        return resp.json().await.map_err(crate::errors::SDKError::from);
                    }
                    if let Some(ra_delay) = Self::parse_retry_after(&resp) {
                        retry_after_used = true;
                        if self.log_level >= LogLevel::Info {
                            log::info!("retry attempt {}/{} for GET {} (retry-after: {:?})", attempt + 1, self.max_retries, url, ra_delay);
                        }
                        tokio::time::sleep(ra_delay).await;
                    }
                    // retryable status, continue loop
                }
                Err(e) => {
                    if self.log_level >= LogLevel::Error {
                        log::error!("connection error: GET {} - {}", url, e);
                    }
                    if attempt == self.max_retries {
                        return Err(crate::errors::SDKError::from(e));
                    }
                    last_err = Some(e);
                }
            }
        }
        Err(crate::errors::SDKError::from(last_err.unwrap()))
    }

    /// Create a new task
    pub async fn create_task(&self, body: &CreateTaskRequest, options: Option<&RequestOptions>) -> Result<Task, crate::errors::SDKError> {
        let mut url = format!("{}{}", self.base_url, "/api/tasks");
        if self.log_level >= LogLevel::Debug {
            log::debug!("request: POST {}", url);
        }
        let effective_timeout = options.and_then(|o| o.timeout).unwrap_or(self.timeout);
        let idempotency_key = {
            let ts = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos();
            let jitter = (rand_jitter() * 1_000_000_000.0) as u64;
            format!("{:x}-{:x}", ts, jitter)
        };
        let is_mutating = matches!("POST", "POST" | "PUT" | "PATCH" | "DELETE");
        let mut last_err: Option<reqwest::Error> = None;
        let mut retry_after_used = false;
        for attempt in 0..=self.max_retries {
            if attempt > 0 && !retry_after_used {
                if self.log_level >= LogLevel::Info {
                    log::info!("retry attempt {}/{} for POST {}", attempt, self.max_retries, url);
                }
                tokio::time::sleep(Self::retry_delay(attempt - 1)).await;
            }
            retry_after_used = false;
            let mut default_headers = HeaderMap::new();
            default_headers.insert("user-agent", HeaderValue::from_str(&format!(
                "taskmanager-sdk/0.2.0 rust {}/{}",
                std::env::consts::OS,
                std::env::consts::ARCH,
            )).unwrap());
            if let Some(ref token) = self.auth_header() {
                default_headers.insert("authorization", HeaderValue::from_str(token).unwrap());
            }
            if is_mutating {
                default_headers.insert("x-idempotency-key", HeaderValue::from_str(&idempotency_key).unwrap());
            }
            // Merge default, client-level, and per-request headers
            let client_overrides: Vec<(HeaderName, Option<HeaderValue>)> = self.headers.iter()
                .map(|(k, v)| (k.clone(), Some(v.clone())))
                .collect();
            let merged = merge_headers(&default_headers, &client_overrides);
            let mut req = self.http.post(&url).timeout(effective_timeout).headers(merged);
            if let Some(opts) = options {
                if let Some(ref hdrs) = opts.headers {
                    for (k, v) in hdrs {
                        req = req.header(k.as_str(), v.as_str());
                    }
                }
            }
            req = req.json(body);
            match req.send().await {
                Ok(resp) => {
                    if self.log_level >= LogLevel::Debug {
                        log::debug!("response: {} for POST {}", resp.status().as_u16(), url);
                    }
                    let status = resp.status().as_u16();
                    if !Self::is_retryable_status(status) || attempt == self.max_retries {
                        // Check for error responses before attempting to deserialize
                        if status < 200 || status >= 300 {
                            let headers: Vec<(String, String)> = resp.headers().iter()
                                .map(|(k, v)| (k.to_string(), v.to_str().unwrap_or("").to_string()))
                                .collect();
                            let body = resp.text().await.unwrap_or_default();
                            if self.log_level >= LogLevel::Error {
                                log::error!("API error: {} POST {}", status, url);
                            }
                            return Err(crate::errors::SDKError::API(
                                crate::errors::APIError::from_response(status, headers, body)
                            ));
                        }
                        let content_length = resp.content_length().unwrap_or(1);
                        if content_length == 0 {
                            return Ok(serde_json::from_str("{}").unwrap());
                        }
                        return resp.json().await.map_err(crate::errors::SDKError::from);
                    }
                    if let Some(ra_delay) = Self::parse_retry_after(&resp) {
                        retry_after_used = true;
                        if self.log_level >= LogLevel::Info {
                            log::info!("retry attempt {}/{} for POST {} (retry-after: {:?})", attempt + 1, self.max_retries, url, ra_delay);
                        }
                        tokio::time::sleep(ra_delay).await;
                    }
                    // retryable status, continue loop
                }
                Err(e) => {
                    if self.log_level >= LogLevel::Error {
                        log::error!("connection error: POST {} - {}", url, e);
                    }
                    if attempt == self.max_retries {
                        return Err(crate::errors::SDKError::from(e));
                    }
                    last_err = Some(e);
                }
            }
        }
        Err(crate::errors::SDKError::from(last_err.unwrap()))
    }

    /// Get a task by ID
    pub async fn get_task(&self, task_id: &str, options: Option<&RequestOptions>) -> Result<Task, crate::errors::SDKError> {
        let mut url = format!("{}{}", self.base_url, format!("/api/tasks/{}", task_id));
        if self.log_level >= LogLevel::Debug {
            log::debug!("request: GET {}", url);
        }
        let effective_timeout = options.and_then(|o| o.timeout).unwrap_or(self.timeout);
        let idempotency_key = {
            let ts = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos();
            let jitter = (rand_jitter() * 1_000_000_000.0) as u64;
            format!("{:x}-{:x}", ts, jitter)
        };
        let is_mutating = matches!("GET", "POST" | "PUT" | "PATCH" | "DELETE");
        let mut last_err: Option<reqwest::Error> = None;
        let mut retry_after_used = false;
        for attempt in 0..=self.max_retries {
            if attempt > 0 && !retry_after_used {
                if self.log_level >= LogLevel::Info {
                    log::info!("retry attempt {}/{} for GET {}", attempt, self.max_retries, url);
                }
                tokio::time::sleep(Self::retry_delay(attempt - 1)).await;
            }
            retry_after_used = false;
            let mut default_headers = HeaderMap::new();
            default_headers.insert("user-agent", HeaderValue::from_str(&format!(
                "taskmanager-sdk/0.2.0 rust {}/{}",
                std::env::consts::OS,
                std::env::consts::ARCH,
            )).unwrap());
            if let Some(ref token) = self.auth_header() {
                default_headers.insert("authorization", HeaderValue::from_str(token).unwrap());
            }
            if is_mutating {
                default_headers.insert("x-idempotency-key", HeaderValue::from_str(&idempotency_key).unwrap());
            }
            // Merge default, client-level, and per-request headers
            let client_overrides: Vec<(HeaderName, Option<HeaderValue>)> = self.headers.iter()
                .map(|(k, v)| (k.clone(), Some(v.clone())))
                .collect();
            let merged = merge_headers(&default_headers, &client_overrides);
            let mut req = self.http.get(&url).timeout(effective_timeout).headers(merged);
            if let Some(opts) = options {
                if let Some(ref hdrs) = opts.headers {
                    for (k, v) in hdrs {
                        req = req.header(k.as_str(), v.as_str());
                    }
                }
            }
            match req.send().await {
                Ok(resp) => {
                    if self.log_level >= LogLevel::Debug {
                        log::debug!("response: {} for GET {}", resp.status().as_u16(), url);
                    }
                    let status = resp.status().as_u16();
                    if !Self::is_retryable_status(status) || attempt == self.max_retries {
                        // Check for error responses before attempting to deserialize
                        if status < 200 || status >= 300 {
                            let headers: Vec<(String, String)> = resp.headers().iter()
                                .map(|(k, v)| (k.to_string(), v.to_str().unwrap_or("").to_string()))
                                .collect();
                            let body = resp.text().await.unwrap_or_default();
                            if self.log_level >= LogLevel::Error {
                                log::error!("API error: {} GET {}", status, url);
                            }
                            return Err(crate::errors::SDKError::API(
                                crate::errors::APIError::from_response(status, headers, body)
                            ));
                        }
                        let content_length = resp.content_length().unwrap_or(1);
                        if content_length == 0 {
                            return Ok(serde_json::from_str("{}").unwrap());
                        }
                        return resp.json().await.map_err(crate::errors::SDKError::from);
                    }
                    if let Some(ra_delay) = Self::parse_retry_after(&resp) {
                        retry_after_used = true;
                        if self.log_level >= LogLevel::Info {
                            log::info!("retry attempt {}/{} for GET {} (retry-after: {:?})", attempt + 1, self.max_retries, url, ra_delay);
                        }
                        tokio::time::sleep(ra_delay).await;
                    }
                    // retryable status, continue loop
                }
                Err(e) => {
                    if self.log_level >= LogLevel::Error {
                        log::error!("connection error: GET {} - {}", url, e);
                    }
                    if attempt == self.max_retries {
                        return Err(crate::errors::SDKError::from(e));
                    }
                    last_err = Some(e);
                }
            }
        }
        Err(crate::errors::SDKError::from(last_err.unwrap()))
    }

    /// Delete a task
    pub async fn delete_task(&self, task_id: &str, options: Option<&RequestOptions>) -> Result<serde_json::Value, crate::errors::SDKError> {
        let mut url = format!("{}{}", self.base_url, format!("/api/tasks/{}", task_id));
        if self.log_level >= LogLevel::Debug {
            log::debug!("request: DELETE {}", url);
        }
        let effective_timeout = options.and_then(|o| o.timeout).unwrap_or(self.timeout);
        let idempotency_key = {
            let ts = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos();
            let jitter = (rand_jitter() * 1_000_000_000.0) as u64;
            format!("{:x}-{:x}", ts, jitter)
        };
        let is_mutating = matches!("DELETE", "POST" | "PUT" | "PATCH" | "DELETE");
        let mut last_err: Option<reqwest::Error> = None;
        let mut retry_after_used = false;
        for attempt in 0..=self.max_retries {
            if attempt > 0 && !retry_after_used {
                if self.log_level >= LogLevel::Info {
                    log::info!("retry attempt {}/{} for DELETE {}", attempt, self.max_retries, url);
                }
                tokio::time::sleep(Self::retry_delay(attempt - 1)).await;
            }
            retry_after_used = false;
            let mut default_headers = HeaderMap::new();
            default_headers.insert("user-agent", HeaderValue::from_str(&format!(
                "taskmanager-sdk/0.2.0 rust {}/{}",
                std::env::consts::OS,
                std::env::consts::ARCH,
            )).unwrap());
            if let Some(ref token) = self.auth_header() {
                default_headers.insert("authorization", HeaderValue::from_str(token).unwrap());
            }
            if is_mutating {
                default_headers.insert("x-idempotency-key", HeaderValue::from_str(&idempotency_key).unwrap());
            }
            // Merge default, client-level, and per-request headers
            let client_overrides: Vec<(HeaderName, Option<HeaderValue>)> = self.headers.iter()
                .map(|(k, v)| (k.clone(), Some(v.clone())))
                .collect();
            let merged = merge_headers(&default_headers, &client_overrides);
            let mut req = self.http.delete(&url).timeout(effective_timeout).headers(merged);
            if let Some(opts) = options {
                if let Some(ref hdrs) = opts.headers {
                    for (k, v) in hdrs {
                        req = req.header(k.as_str(), v.as_str());
                    }
                }
            }
            match req.send().await {
                Ok(resp) => {
                    if self.log_level >= LogLevel::Debug {
                        log::debug!("response: {} for DELETE {}", resp.status().as_u16(), url);
                    }
                    let status = resp.status().as_u16();
                    if !Self::is_retryable_status(status) || attempt == self.max_retries {
                        // Check for error responses before attempting to deserialize
                        if status < 200 || status >= 300 {
                            let headers: Vec<(String, String)> = resp.headers().iter()
                                .map(|(k, v)| (k.to_string(), v.to_str().unwrap_or("").to_string()))
                                .collect();
                            let body = resp.text().await.unwrap_or_default();
                            if self.log_level >= LogLevel::Error {
                                log::error!("API error: {} DELETE {}", status, url);
                            }
                            return Err(crate::errors::SDKError::API(
                                crate::errors::APIError::from_response(status, headers, body)
                            ));
                        }
                        let content_length = resp.content_length().unwrap_or(1);
                        if content_length == 0 {
                            return Ok(serde_json::from_str("{}").unwrap());
                        }
                        return resp.json().await.map_err(crate::errors::SDKError::from);
                    }
                    if let Some(ra_delay) = Self::parse_retry_after(&resp) {
                        retry_after_used = true;
                        if self.log_level >= LogLevel::Info {
                            log::info!("retry attempt {}/{} for DELETE {} (retry-after: {:?})", attempt + 1, self.max_retries, url, ra_delay);
                        }
                        tokio::time::sleep(ra_delay).await;
                    }
                    // retryable status, continue loop
                }
                Err(e) => {
                    if self.log_level >= LogLevel::Error {
                        log::error!("connection error: DELETE {} - {}", url, e);
                    }
                    if attempt == self.max_retries {
                        return Err(crate::errors::SDKError::from(e));
                    }
                    last_err = Some(e);
                }
            }
        }
        Err(crate::errors::SDKError::from(last_err.unwrap()))
    }

    /// Update a task
    pub async fn update_task(&self, task_id: &str, body: &UpdateTaskRequest, options: Option<&RequestOptions>) -> Result<Task, crate::errors::SDKError> {
        let mut url = format!("{}{}", self.base_url, format!("/api/tasks/{}", task_id));
        if self.log_level >= LogLevel::Debug {
            log::debug!("request: PATCH {}", url);
        }
        let effective_timeout = options.and_then(|o| o.timeout).unwrap_or(self.timeout);
        let idempotency_key = {
            let ts = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos();
            let jitter = (rand_jitter() * 1_000_000_000.0) as u64;
            format!("{:x}-{:x}", ts, jitter)
        };
        let is_mutating = matches!("PATCH", "POST" | "PUT" | "PATCH" | "DELETE");
        let mut last_err: Option<reqwest::Error> = None;
        let mut retry_after_used = false;
        for attempt in 0..=self.max_retries {
            if attempt > 0 && !retry_after_used {
                if self.log_level >= LogLevel::Info {
                    log::info!("retry attempt {}/{} for PATCH {}", attempt, self.max_retries, url);
                }
                tokio::time::sleep(Self::retry_delay(attempt - 1)).await;
            }
            retry_after_used = false;
            let mut default_headers = HeaderMap::new();
            default_headers.insert("user-agent", HeaderValue::from_str(&format!(
                "taskmanager-sdk/0.2.0 rust {}/{}",
                std::env::consts::OS,
                std::env::consts::ARCH,
            )).unwrap());
            if let Some(ref token) = self.auth_header() {
                default_headers.insert("authorization", HeaderValue::from_str(token).unwrap());
            }
            if is_mutating {
                default_headers.insert("x-idempotency-key", HeaderValue::from_str(&idempotency_key).unwrap());
            }
            // Merge default, client-level, and per-request headers
            let client_overrides: Vec<(HeaderName, Option<HeaderValue>)> = self.headers.iter()
                .map(|(k, v)| (k.clone(), Some(v.clone())))
                .collect();
            let merged = merge_headers(&default_headers, &client_overrides);
            let mut req = self.http.patch(&url).timeout(effective_timeout).headers(merged);
            if let Some(opts) = options {
                if let Some(ref hdrs) = opts.headers {
                    for (k, v) in hdrs {
                        req = req.header(k.as_str(), v.as_str());
                    }
                }
            }
            req = req.json(body);
            match req.send().await {
                Ok(resp) => {
                    if self.log_level >= LogLevel::Debug {
                        log::debug!("response: {} for PATCH {}", resp.status().as_u16(), url);
                    }
                    let status = resp.status().as_u16();
                    if !Self::is_retryable_status(status) || attempt == self.max_retries {
                        // Check for error responses before attempting to deserialize
                        if status < 200 || status >= 300 {
                            let headers: Vec<(String, String)> = resp.headers().iter()
                                .map(|(k, v)| (k.to_string(), v.to_str().unwrap_or("").to_string()))
                                .collect();
                            let body = resp.text().await.unwrap_or_default();
                            if self.log_level >= LogLevel::Error {
                                log::error!("API error: {} PATCH {}", status, url);
                            }
                            return Err(crate::errors::SDKError::API(
                                crate::errors::APIError::from_response(status, headers, body)
                            ));
                        }
                        let content_length = resp.content_length().unwrap_or(1);
                        if content_length == 0 {
                            return Ok(serde_json::from_str("{}").unwrap());
                        }
                        return resp.json().await.map_err(crate::errors::SDKError::from);
                    }
                    if let Some(ra_delay) = Self::parse_retry_after(&resp) {
                        retry_after_used = true;
                        if self.log_level >= LogLevel::Info {
                            log::info!("retry attempt {}/{} for PATCH {} (retry-after: {:?})", attempt + 1, self.max_retries, url, ra_delay);
                        }
                        tokio::time::sleep(ra_delay).await;
                    }
                    // retryable status, continue loop
                }
                Err(e) => {
                    if self.log_level >= LogLevel::Error {
                        log::error!("connection error: PATCH {} - {}", url, e);
                    }
                    if attempt == self.max_retries {
                        return Err(crate::errors::SDKError::from(e));
                    }
                    last_err = Some(e);
                }
            }
        }
        Err(crate::errors::SDKError::from(last_err.unwrap()))
    }

    /// Mark a task as done
    pub async fn complete_task(&self, task_id: &str, body: &impl serde::Serialize, options: Option<&RequestOptions>) -> Result<Task, crate::errors::SDKError> {
        let mut url = format!("{}{}", self.base_url, format!("/api/tasks/{}/complete", task_id));
        if self.log_level >= LogLevel::Debug {
            log::debug!("request: POST {}", url);
        }
        let effective_timeout = options.and_then(|o| o.timeout).unwrap_or(self.timeout);
        let idempotency_key = {
            let ts = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_nanos();
            let jitter = (rand_jitter() * 1_000_000_000.0) as u64;
            format!("{:x}-{:x}", ts, jitter)
        };
        let is_mutating = matches!("POST", "POST" | "PUT" | "PATCH" | "DELETE");
        let mut last_err: Option<reqwest::Error> = None;
        let mut retry_after_used = false;
        for attempt in 0..=self.max_retries {
            if attempt > 0 && !retry_after_used {
                if self.log_level >= LogLevel::Info {
                    log::info!("retry attempt {}/{} for POST {}", attempt, self.max_retries, url);
                }
                tokio::time::sleep(Self::retry_delay(attempt - 1)).await;
            }
            retry_after_used = false;
            let mut default_headers = HeaderMap::new();
            default_headers.insert("user-agent", HeaderValue::from_str(&format!(
                "taskmanager-sdk/0.2.0 rust {}/{}",
                std::env::consts::OS,
                std::env::consts::ARCH,
            )).unwrap());
            if let Some(ref token) = self.auth_header() {
                default_headers.insert("authorization", HeaderValue::from_str(token).unwrap());
            }
            if is_mutating {
                default_headers.insert("x-idempotency-key", HeaderValue::from_str(&idempotency_key).unwrap());
            }
            // Merge default, client-level, and per-request headers
            let client_overrides: Vec<(HeaderName, Option<HeaderValue>)> = self.headers.iter()
                .map(|(k, v)| (k.clone(), Some(v.clone())))
                .collect();
            let merged = merge_headers(&default_headers, &client_overrides);
            let mut req = self.http.post(&url).timeout(effective_timeout).headers(merged);
            if let Some(opts) = options {
                if let Some(ref hdrs) = opts.headers {
                    for (k, v) in hdrs {
                        req = req.header(k.as_str(), v.as_str());
                    }
                }
            }
            req = req.json(body);
            match req.send().await {
                Ok(resp) => {
                    if self.log_level >= LogLevel::Debug {
                        log::debug!("response: {} for POST {}", resp.status().as_u16(), url);
                    }
                    let status = resp.status().as_u16();
                    if !Self::is_retryable_status(status) || attempt == self.max_retries {
                        // Check for error responses before attempting to deserialize
                        if status < 200 || status >= 300 {
                            let headers: Vec<(String, String)> = resp.headers().iter()
                                .map(|(k, v)| (k.to_string(), v.to_str().unwrap_or("").to_string()))
                                .collect();
                            let body = resp.text().await.unwrap_or_default();
                            if self.log_level >= LogLevel::Error {
                                log::error!("API error: {} POST {}", status, url);
                            }
                            return Err(crate::errors::SDKError::API(
                                crate::errors::APIError::from_response(status, headers, body)
                            ));
                        }
                        let content_length = resp.content_length().unwrap_or(1);
                        if content_length == 0 {
                            return Ok(serde_json::from_str("{}").unwrap());
                        }
                        return resp.json().await.map_err(crate::errors::SDKError::from);
                    }
                    if let Some(ra_delay) = Self::parse_retry_after(&resp) {
                        retry_after_used = true;
                        if self.log_level >= LogLevel::Info {
                            log::info!("retry attempt {}/{} for POST {} (retry-after: {:?})", attempt + 1, self.max_retries, url, ra_delay);
                        }
                        tokio::time::sleep(ra_delay).await;
                    }
                    // retryable status, continue loop
                }
                Err(e) => {
                    if self.log_level >= LogLevel::Error {
                        log::error!("connection error: POST {} - {}", url, e);
                    }
                    if attempt == self.max_retries {
                        return Err(crate::errors::SDKError::from(e));
                    }
                    last_err = Some(e);
                }
            }
        }
        Err(crate::errors::SDKError::from(last_err.unwrap()))
    }

}

/// Simple jitter factor between 0.0 and 1.0 using basic time-based seed
fn rand_jitter() -> f64 {
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .subsec_nanos();
    (nanos % 1000) as f64 / 1000.0
}
