// Generated by Sterling SDK Generator
// Task Manager API v0.2.0

use std::fmt;

/// Base error type for the TaskmanagerSdk SDK.
#[derive(Debug)]
pub enum SDKError {
    /// HTTP error response from the API.
    API(APIError),
    /// Could not connect to the API.
    Connection(ConnectionError),
    /// Request serialization or response deserialization error.
    Serialization(String),
    /// Underlying HTTP client error.
    Http(reqwest::Error),
}

impl fmt::Display for SDKError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SDKError::API(e) => write!(f, "{}", e),
            SDKError::Connection(e) => write!(f, "Connection error: {}", e.message),
            SDKError::Serialization(msg) => write!(f, "Serialization error: {}", msg),
            SDKError::Http(e) => write!(f, "HTTP error: {}", e),
        }
    }
}

impl std::error::Error for SDKError {}

impl From<reqwest::Error> for SDKError {
    fn from(err: reqwest::Error) -> Self {
        if err.is_connect() || err.is_timeout() {
            return SDKError::Connection(ConnectionError {
                message: err.to_string(),
                is_timeout: err.is_timeout(),
            });
        }
        SDKError::Http(err)
    }
}

/// Represents an error response from the API with status code and body.
#[derive(Debug)]
pub struct APIError {
    pub status: u16,
    pub headers: Vec<(String, String)>,
    pub body: String,
    pub kind: APIErrorKind,
}

impl std::error::Error for APIError {}

impl fmt::Display for APIError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} {}", self.status, self.body)
    }
}

impl APIError {
    pub fn from_response(status: u16, headers: Vec<(String, String)>, body: String) -> Self {
        let kind = match status {
            400 => APIErrorKind::BadRequest,
            401 => APIErrorKind::Authentication,
            403 => APIErrorKind::PermissionDenied,
            404 => APIErrorKind::NotFound,
            409 => APIErrorKind::Conflict,
            422 => APIErrorKind::UnprocessableEntity,
            429 => APIErrorKind::RateLimit,
            500..=599 => APIErrorKind::InternalServer,
            _ => APIErrorKind::Other,
        };
        Self { status, headers, body, kind }
    }

    /// Extract the error message from the response body.
    ///
    /// If the body is JSON with an `"error"` or `"message"` field, returns that.
    /// Otherwise returns the raw body text.
    pub fn error_message(&self) -> String {
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(&self.body) {
            if let Some(msg) = v.get("error").and_then(|v| v.as_str()) {
                return msg.to_string();
            }
            if let Some(msg) = v.get("message").and_then(|v| v.as_str()) {
                return msg.to_string();
            }
        }
        self.body.clone()
    }
}

/// Categorization of API error responses by status code.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum APIErrorKind {
    BadRequest,
    Authentication,
    PermissionDenied,
    NotFound,
    Conflict,
    UnprocessableEntity,
    RateLimit,
    InternalServer,
    Other,
}

/// Error for connection failures.
#[derive(Debug)]
pub struct ConnectionError {
    pub message: String,
    pub is_timeout: bool,
}
