// Generated by Sterling SDK Generator
// Task Manager API v0.2.0

use serde::{Deserialize, Serialize};

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Task {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<String>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "priority")]
    pub priority: i64,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "due_date")]
    pub due_date: Option<String>,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TaskListResponse {
    #[serde(rename = "tasks")]
    pub tasks: Vec<Task>,
    #[serde(rename = "total")]
    pub total: i64,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ErrorResponse {
    /// Human-readable error message
    #[serde(rename = "error")]
    pub error: String,
    /// Always false for errors
    #[serde(rename = "success")]
    pub success: bool,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateTaskRequest {
    /// Task title (required)
    #[serde(rename = "title")]
    pub title: String,
    /// Optional description
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<String>,
    /// Priority (0 = default)
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "priority")]
    pub priority: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "due_date")]
    pub due_date: Option<String>,
}

/// 
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UpdateTaskRequest {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "title")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "status")]
    pub status: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "priority")]
    pub priority: Option<i64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "due_date")]
    pub due_date: Option<String>,
}


// ── Params types for operations with query parameters ───────────────

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ListTasksParams {
    /// Filter by task status
    pub status: Option<String>,
    /// Maximum number of tasks to return
    pub limit: Option<i64>,
}

